[package]
name = "calcite_proc_macros"
version = "0.1.3"
authors = ["Srinivasa <m.srinivasa1234@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A helper library for calcite"

[dependencies]
quote = "1.0.8"
proc-macro2 = "1.0.24"

[lib]
proc-macro = true
