name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x      
    - name: Run sync
      run: |
       cargo build --example sync
       deno run --unstable --allow-plugin --allow-read --allow-write examples/sync.ts
    - name: Run async
      run: |
       cargo build --example async
       deno run --unstable --allow-plugin --allow-read --allow-write examples/async.ts
